# # # # env:
# # # #   BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: 'rt://tf-trial/workspaces/jfrog-ws1/test.txt'
# # # #   BUILDKITE_ARTIFACTORY_URL: 'https://personaluse4.jfrog.io/artifactory'
# # # #   BUILDKITE_ARTIFACTORY_USER: 'athreya'
# # # #   BUILDKITE_ARTIFACTORY_PASSWORD: 'Srinivas@24'
# # # #   $$BUILDKITE_ARTIFACT_PATHS: 'https://personaluse4.jfrog.io/artifactory/tf-trial/workspaces/jfrog-ws1/'

# # # # steps:
# # # # - label: "Graceful Termination Test"
# # # #   command: |
# # # #     trap "echo 'This command indicates that we Received a SIGTERM and Ideally we should starting graceful shutdown... check the signal time from here'; sleep 90; echo 'Graceful shutdown complete.'" SIGTERM
# # # #     echo "SSatrting a process that runs for 90 seconds to check"
# # # #     sleep 90
# # # #     echo "Long-running process completed."

# # # steps:
# # # - label: "job retry vs rebuild times test :rocket:"
# # #   command: |
# # #     echo "this is a test for rebuild and retry $BUILDKITE_BUILD_ID and Job ID $BUILDKITE_JOB_ID"
# # #     sleep 120
# # #     exit 1
# # #   timeout_in_minutes: 1
# # #   key: "this"

# # # - label: "send results to slack"
# # #   command: echo "test"
# # #   # agents:
# # #   #   queue: "another_test"
# # #   priority: 0
# # #   notify:
# # #   - slack: "#slack_notification_test"
# # #   timeout_in_minutes: 1
# # #   depends_on: "this"
# # #   allow_dependency_failure: false



# # # steps:
# # # - group: ":lock_with_ink_pen: Security Audits"
# # #   key: "audits"
# # #   steps:
# # #   - label: ":brakeman: Brakeman"
# # #     command: "echo step 1 passed"
# # #   - label: ":bundleaudit: Bundle Audit"
# # #     command: "echo step 2 passed"
# # #   - label: ":yarn: Yarn Audit"
# # #     command: "echo step p3 assed"
# # #   - label: ":yarn: Outdated Check"
# # #     command: exit 1
# # #   notify:
# # #   - github_commit_status:
# # #       context: "group status check at bottom"


# # steps:
# # - group: "📦 Group1"
# #   key: firstbuild
# #   notify:
# #   - github_commit_status:
# #       context: "my-group-status"
# #   steps:
# #   - label: ":pipeline:Group1-Step1"
# #     command: echo "This is a success."
# #     key: step1
# #   - label: ":pipeline:Group1-step2"
# #     command: echo "hi"
# #     depends_on:
# #     - step1
# #     key: step2



# # - group: "📦 Group2"
# #   depends_on:
# #   - firstbuild
# #   notify:
# #   - github_commit_status:
# #       context: "my-group-status-2"
# #   steps:
# #   - label: ":pipeline:Group2-Step1"
# #     command: echo "This is a success."
# #     key: group2-step1
# #   - label: ":pipeline:Group2-step2"
# #     command: echo "works"
# #     depends_on:
# #     - group2-step1
# #     key: build2-step2





# # - if: "!build.pull_request.draft && build.pull_request.id != null"
# #   group: "📦 Group3"
# #   depends_on:
# #   - firstbuild
# #   notify:
# #   - github_commit_status:
# #       context: "my-group-status-2"
# #   steps:
# #   - label: ":pipeline:Group2-Step1"
# #     command: echo "This is a success."
# #     key: group3-step1
# #   - label: ":pipeline:Group2-step2"
# #     command: exit 1
# #     depends_on:
# #     - group3-step1
# #     key: build2-step2


# steps:
# - key: "firstbuild"
#   group: "📦 Group1"
#   steps:
#   - key: "step1"
#     label: ":pipeline:Group1-Step1"
#     command: "echo \"This is a success.\""
#   - key: "step2"
#     label: ":pipeline:Group1-step2"
#     command: exit 1
#   notify:
#   - github_commit_status:
#       context: "my-group-status"

# - group: "📦 Group2"
#   steps:
#   - key: "group2-step1"
#     label: ":pipeline:Group2-Step1"
#     command: "echo \"This is a success.\""
#   - key: "build2-step2"
#     label: ":pipeline:Group2-step2"
#     command: exit 1
#   notify:
#   - github_commit_status:
#       context: "my-group-status-2"
#   depends_on:
#   - "firstbuild"
# if: "!build.pull_request.draft && build.pull_request.id != null"


# steps:
# - if: "!build.pull_request.draft"
#   key: "ci"
#   group: "Continuous Integration :buildkite:"
#   steps:
#   - label: "Format Prettier :barber:"
#     notify:
#     - github_commit_status:
#         context: "Frontend E2E/format-prettier"
#     command: exit 1

#   - label: "Lint :lint-roller:"
#     notify:
#     - github_commit_status:
#         context: "Frontend E2E/lint"
#     command: echo "hi"



# - group: "Mabl PR Tests"
#   key: "mabl"
#   steps:
#   - label: "Wait for Render environment to be ready"
#     command: echo "hi"
#   - wait
#   - label: "Run mabl tests against Render preview"
#     command: echo "hi"
#   notify:
#   - github_commit_status:
#       context: "Frontend E2E/mabl-tests"
#   depends_on:
#   - "ci"
# - if: "!build.pull_request.draft && build.pull_request.id != null"

# steps:
# - label: "Merge branch 'dev' into SCALE-226-FE-Show-Manage-Libraries-Button-UI-only-for-the-allowed-roles"
#   command: echo "hi"

# - label: "This is the step from the master branch and the order of this step is - one"
#   command: echo "hi"

# - label: "This is the step from the master branch and the order of this step is - two"
#   command: echo "hi"

# - label: "env var step"
#   env:
#     CMD_ENV_NEW: ls
#   command: echo $$CMD_ENV_NEW

# steps:
# - label: "signed pipeline check"
#   commands:
#   - "grep 'checkoutskip2' README.md > /opt/homebrew/etc/buildkite-agent/hooks/my_var.txt"

# - block: ":rocket: Are we ready???"

# - wait # This will wait for the block step to be manually unblocked

# - label: "dependency step"
#   command: "echo 'This step runs after the block step is unblocked'"

# - wait # Ensures the previous command completes before moving to the final step

# - label: "final step"
#   command: "echo 'finished'"
# env:
#   # This block defines other environment variables needed at the step level
#   MY_VAR: echo "$$MY_VAR"
# signature:
#   algorithm: EdDSA
#   signed_fields:
#   - command
#   value: Ax-8fPRDBJjnVYePpSnr-Saa63FXGdc0REbcSEpqDao


# steps:
# - label: Hello World!
#   command: echo Hello World, Lets start!
#   parallelism: 3
#   agents:
#     queue: kubernetes


# steps:
# - label: "Only run on PR merge"
#   command: echo "Only step 1 is running"
#   if: build.message =~ /Triggered / || build.message =~ /Merge /


# - label: "Regular Step"
#   command: echo "regular step is running"
#   if: build.message =~ /Merge /

# ######

# steps:
# - label: "Run tests and collect analytics"
#   commands:
#   - "pip install --upgrade pip"
#   - "pip install -r requirements.txt"
#   - "pip list" # Lists installed packages
#   - "which pytest" # Finds where pytest is installed
#   - "python -m pytest" # Use python -m to ensure pytest runs correctly
#   plugins:
#   - docker#v3.8.0:
#       image: "python:3.9"
#       environment:
#       - BUILDKITE_ANALYTICS_TOKEN
#   env:
#     BUILDKITE_ANALYTICS_TOKEN: "AvjDAf5Egs317ia4bZiuDUKq"


# steps:
# - label: "Use Test Var"
#   command:
#   - "echo 'Using MY_SECRET:'"
#   - "echo $$TEST_VAR"

## assigning an IAM role to your ec2 instance. Make sure that role has the permission to read and write secrets
# - label: "Example step using AWS Secrets Manager"
#   plugins:
#   - seek-oss/aws-sm:
#       env:
#         MY_SECRET_ENV_VAR: "arn:aws:secretsmanager:us-east-1:222754863288:secret:bktoken-HNMm9x"  ### This one is the arn of your secret in secrets manager
#   command: "echo 'Hello, world! My secret is $MY_SECRET_ENV_VAR'"

# steps:
# - label: "Example step using AWS Secrets Manager"
#   commands: 'echo \$MY_TEST'
#   plugins:
#   - seek-oss/aws-sm#v1.0.0:
#       env:
#         MY_TEST: "arn:aws:secretsmanager:us-east-1:222754863288:secret:bktoken-HNMm9x"


# steps:

# - label: "Print Environment Variables"
#   command: "echo $BUILDKITE_S3_ENDPOINT && sleep 400 "
#   key: "this"

# - label: "Print Environment Variables"
#   command: "echo $BUILDKITE_S3_ENDPOINT && sleep 400 "
#   depends_on: "this"

# - label: "Generate and upload an artifact"
#   commands:
#   - echo "Hello, Buildkite using MinIO!" > artifact.txt
#   artifact_paths: "artifact.txt"

# {"steps": {"command": "echo 'Hello, world!'", "label": ":echo: Hello"},}


# steps:

# - label: "trigger staging smoke test"

#   key: "trigger-staging-smoke-test"

#   command: echo "test"

#   env:

#     # AURORA_BAZEL_CONFIG_CI: "true"

#     # AGENT_QUEUE_SUFFIX: "staging"

#     QUEUE_CAPABILITIES: {"custom": "true", "ami_id": "$AMI_ID"}


# steps:
# - group: "Deployment Pipeline"
#   steps:
#   - block: "Approve Deployment"
#     fields:
#     - text: "Approver Name"
#       key: "approver_name"
#       required: true
#     - select: "Environment"
#       key: "environment"
#       options:
#       - label: "Staging"
#         value: "staging"
#       - label: "Production"
#         value: "production"
#       required: true

#   - input: "Provide Deployment Details"
#     fields:
#     - text: "Deployment Version"
#       key: "deployment_version"
#       required: true
#     - select: "Rollback Required"
#       key: "rollback_required"
#       options:
#       - label: "Yes"
#         value: "yes"
#       - label: "No"
#         value: "no"
#       required: true

# steps:
# - command: buildkite-agent meta-data get "Test-Key-Doesn't_exist" --default "Returning this value if mete-data doesn't exist"

# steps:
# - label: ":rocket: Testing bk local run"
#   command: echo "local run works" && exit 1

# - label: "testing cancel_on_build_failing"
#   command: sleep 600
#   cancel_on_build_failing: true


# steps:
# - label: "Build"
#   command:
#   - mkdir -p artifacts
#   - echo "Hello, Buildkite!" > greeting.txt
#   - echo "Build step completed."
#   artifact_paths:
#   - ./greeting.txt

# - label: "Test"
#   command:
#   - buildkite-agent artifact download "greeting.txt" .
#   - cat greeting.txt
#   - echo "Test step completed."

# agents:
#   queue: Hosted_Agents
# steps:
# # - label: "Generate Greeting"
# #   command: "echo Hello, World! > greeting.txt"
# #   artifact_paths: "greeting.txt"

# - label: 'Build'
#   command: buildkite-agent artifact upload greeting.txt

# steps:
#   - label: ":hammer: Build"
#     command: echo "Hello Friends!"
#   - wait

#   - label: "Check Build Status and Notify"
#     command: echo "check-and-notify.sh"

# notify:
#   slack: "@athreya"
#   if: build.state == "passed"

# .buildkite/pipeline.yml
# .buildkite/pipeline.yml
# env:
#   COOL_PASSWORD: "hahaha"

# steps:
# - label: ":hammer: Example Script"
#   command: "echo $COOL_PASSWORD"


# steps:
# - label: "Build Step"
#   command: echo "$SAMPLE"

# steps:
# - label: "Create Artifact"
#   commands:
#   - mkdir -p test1 # Ensure the test1 directory exists
#   - echo "Hello, Buildkite!" > hello.txt
#   - pwd >> test1/test123.txt # Append pwd output to test123.txt in test1 folder
#   - echo "$BUILDKITE_BUILD_CHECKOUT_PATH"
#   - ls
#   - buildkite-agent artifact upload "test1/*"

# - label: "Download Artifacts"
#   commands:
#   # Ensure the test1 directory exists
# - buildkite-agent artifact download "test1/abc.txt" . # Ensure the correct download path
# - cat test1/abc.txt # Ensure the correct path




# --build "018f963e-ce8b-4ba8-9aaa-4e3c973811a8"


# cache:
#   id: icfse
#   s3:
#     bucket: deepmatter-buildkite-cache-production
#   key: v1-cache-{{ id }}-{{ git.commit }}
#   paths:
#   - "."
#   backend: s3
#   restore-keys:
#   - v1-cache-{{ id }}-{{ git.commit }}


# steps:
# - block: ":mag: Build Details"
#   if: build.source != "webhook"
#   fields:
#   - text: "Deployable Target"
#     key: "deployable-target"
#     hint: "e.g. treasury2"
#     required: trueAWS
#   - select: "Language"
#     key: "language"
#     required: true
#     default: "py3"
#     options:
#     - label: "Python 3"
#       value: "py3"
#     - label: "Kotlin"
#       value: "kotlin"
#     - label: "Python 2"
#       value: "py2"

# - label: "Run conditional build trigger"
#   command: ./condition.sh
#   env:
#     CONDITION: "true"


# steps:
# - label: "Timeout Example"
#   command: "echo \"This is a job step that will timeout.\" > output.log\nsleep 120 # Simulate a long-running process\necho \"This should not be reached if timeout is working.\" \n# buildkite-agent artifact upload output.log\n"
#   timeout_in_minutes: 1 # Set a short timeout for demonstration purposes
#   artifact_paths: "output.log"

# - label: "Generate Artifact :alien:"
#   command: "echo \"Generating output.log\"\necho \"This is an artifact file.\" \n"
#   artifact_paths: "output.log"

# - label: "Keyboard test :keyboard:"
#   command: echo "keyboard is working fine"

steps:
- label: "Run Tests"
  command: echo "run-tests.sh" && buildkite-agent meta-data set "foo" "bar again"
  parallelism: 2 # Adjust the number of parallel jobs as needed
  -plugins:
    -detect-clowns#v2.0.0: ~




